package mvc.view;

import mvc.model.Complexity;
import mvc.model.UniqueOperand;
import mvc.model.UniqueOperator;
import mvc.model.ASTParser;
import japa.parser.ParseException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import mvc.controller.SystemControl;
import mvc.model.DataCyclomatic;
import mvc.model.DataHalstead;
import mvc.model.DataParsingCode;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author F Revolusioner
 */
public class MainUI extends javax.swing.JFrame {

    private final Complexity c;
    private final SystemControl sc;
    private final DataParsingCode dataPC;
    private final DataHalstead dataHV;
    private final DataCyclomatic dataCC;
    private final ASTParser astParser;
    private final UniqueOperator uOprt;
    private final UniqueOperand uOprn;

    /**
     * Creates new form NewJFrame
     */
    public MainUI() {
        astParser = new ASTParser();
        uOprt = new UniqueOperator();
        uOprn = new UniqueOperand();
        dataPC = new DataParsingCode();
        dataHV = new DataHalstead();
        dataCC = new DataCyclomatic();
        sc = new SystemControl();
        c = new Complexity(astParser, uOprt, uOprn);
        //m.setModel(this);
        initComponents();
        btnHitungKompleksitas.setMnemonic('K');
        btnLogHalstead.setMnemonic('H');
        btnLogCyclomatic.setMnemonic('C');
        btnDeleteLog.setMnemonic('D');
    }

    public JTextArea logArea() {
        return showLog;
    }

    public void showParsingCode(DataParsingCode dataPC) {
        dataPC.readParsingCode(this);
    }

    public void showLogHalstead(DataHalstead dataHV) {
        dataHV.readLogHalstead(this);
    }

    public void showLogCyclomatic(DataCyclomatic dataCC) {
        dataCC.readLogCyclomatic(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jScrollPane1 = new javax.swing.JScrollPane();
        showLog = new javax.swing.JTextArea();
        btnDeleteLog = new javax.swing.JButton();
        btnLogCyclomatic = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        btnLogHalstead = new javax.swing.JButton();
        btnHitungKompleksitas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[ Sistem Perhitungan Kompleksitas Kode Sumber Java ]");
        getContentPane().setLayout(null);

        showLog.setEditable(false);
        showLog.setColumns(20);
        showLog.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        showLog.setRows(5);
        showLog.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Log Hasil Perhitungan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bookman Old Style", 3, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        jScrollPane1.setViewportView(showLog);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(5, 67, 550, 335);

        btnDeleteLog.setBackground(new java.awt.Color(0, 0, 0));
        btnDeleteLog.setFont(new java.awt.Font("Haettenschweiler", 0, 22)); // NOI18N
        btnDeleteLog.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteLog.setText("Del Log");
        btnDeleteLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLogActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteLog);
        btnDeleteLog.setBounds(710, 70, 103, 330);

        btnLogCyclomatic.setBackground(new java.awt.Color(0, 0, 0));
        btnLogCyclomatic.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        btnLogCyclomatic.setForeground(new java.awt.Color(255, 255, 255));
        btnLogCyclomatic.setText("Cyclomatic");
        btnLogCyclomatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogCyclomaticActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogCyclomatic);
        btnLogCyclomatic.setBounds(560, 230, 150, 170);

        jSeparator2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(-26, 56, 950, 5);

        jSeparator1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(-26, 408, 950, 5);

        btnLogHalstead.setBackground(new java.awt.Color(0, 0, 0));
        btnLogHalstead.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        btnLogHalstead.setForeground(new java.awt.Color(255, 255, 255));
        btnLogHalstead.setText("Halstead");
        btnLogHalstead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogHalsteadActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogHalstead);
        btnLogHalstead.setBounds(560, 70, 150, 160);

        btnHitungKompleksitas.setBackground(new java.awt.Color(0, 0, 0));
        btnHitungKompleksitas.setFont(new java.awt.Font("Haettenschweiler", 0, 22)); // NOI18N
        btnHitungKompleksitas.setForeground(new java.awt.Color(255, 255, 255));
        btnHitungKompleksitas.setText("Hitung Kompleksitas");
        btnHitungKompleksitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungKompleksitasActionPerformed(evt);
            }
        });
        getContentPane().add(btnHitungKompleksitas);
        btnHitungKompleksitas.setBounds(3, 10, 810, 40);

        setSize(new java.awt.Dimension(824, 476));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLogActionPerformed
        try {
            // TODO add your handling code here:
            sc.deleteLog(this, dataHV, dataCC);
        } catch (IOException | ParseException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteLogActionPerformed

    private void btnLogCyclomaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogCyclomaticActionPerformed
        try {
            // TODO add your handling code here:
            sc.lihatHasilCyclomatic(this, dataCC);
        } catch (IOException | ParseException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLogCyclomaticActionPerformed

    private void btnLogHalsteadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogHalsteadActionPerformed
        try {
            // TODO add your handling code here:
            sc.lihatHasilHalstead(this, dataHV);
        } catch (IOException | ParseException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLogHalsteadActionPerformed

    private void btnHitungKompleksitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungKompleksitasActionPerformed
        try {
            // TODO add your handling code here:
            sc.hitungKompleksitas(this, astParser, dataPC, uOprt, uOprn);
        } catch (IOException | ParseException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnHitungKompleksitasActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.Exception
     */
    public static void main(String[] args) throws Exception {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            com.jtattoo.plaf.noire.NoireLookAndFeel.setTheme("Large-Font", "Java Swing", "");
            UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        /*----------------------------------------------------------------------------------*/
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MainUI frame = new MainUI();
                frame.setVisible(true);

                FileOutputStream fileLog = null;
                try {
                    fileLog = new FileOutputStream("D:/UPDATE_SIDANG/SIPKOM/parsingCode.txt");
                } catch (FileNotFoundException ex) {
                    JOptionPane.showMessageDialog(null, "Silahkan Anda sesuaikan direktori penyimpanan file pada komputer Anda terlebih dulu.", "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
                    JOptionPane.showMessageDialog(null, "Ubah direktori pada class MainUI, Complexity, DataParsingCode, DataHalstead dan DataCyclomatic.", "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
                    System.exit(1);
                    Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                mvc.model.ASTParser.TeePrintStream logParsingCode = new mvc.model.ASTParser.TeePrintStream(fileLog, System.out);
                System.setOut(logParsingCode);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteLog;
    private javax.swing.JButton btnHitungKompleksitas;
    private javax.swing.JButton btnLogCyclomatic;
    private javax.swing.JButton btnLogHalstead;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea showLog;
    // End of variables declaration//GEN-END:variables
}
